### ISSUE TITLE
parsing metadata should catch ENOENT

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_cobol#169]
~~~
Completed scanning all COBOL files in workspace              (77841.00ms)
Error:processAllFilesInWorkspaces/1
Error: ENOENT: no such file or directory, scandir '/home/me/test/src/typo'
	at Object.readdirSync (fs.js:795:3)
	at Object.fs.readdirSync (electron/js2c/asar.js:605:39)
	at Object.fs.readdirSync (electron/js2c/asar.js:605:39)
	at Function.processAllFilesDirectory (/home/me/.vscode-oss/extensions/bitlang.cobol-6.5.18/out/vscobolquickparse.js:109:29)
	at Function.processAllFilesInWorkspaces (/home/me/.vscode-oss/extensions/bitlang.cobol-6.5.18/out/vscobolquickparse.js:86:43)
	at /home/me/.vscode-oss/extensions/bitlang.cobol-6.5.18/out/extension.js:411:41
	at new Promise (<anonymous>)
	at /home/me/.vscode-oss/extensions/bitlang.cobol-6.5.18/out/extension.js:410:16
	at _executeContributedCommand (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:631:163)
	at _.$executeContributedCommand (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:631:538)
	at m._doInvokeHandler (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:683)
	at m._invokeHandler (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:801:375)
	at m._receiveRequest (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:14)
	at m._receiveOneMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:798:832)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:797:34
	at l.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
	at v.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:744
	at l.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
	at v.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:849)
	at t.PersistentProtocol._receiveMessage (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:276)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:357
	at l.fire (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:45:801)
	at p.acceptChunk (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:393)
	at /usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:753
	at Socket.t (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:826)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
Completed scanning all COBOL files in workspace              (1309.00ms)
~~~

**Comment by spgennard** [comment]
It does catch the exception and for diag purposes it shows it, thus allowing you to correct your configuration issue.

**Comment by GitMensch** [comment]
It is good that the error is catched, I suggest to not output the stacktrace and instead "this looks like an extension error" the point of "hey, I had a typo" is easier to get.

**Comment by GitMensch** [comment]
@spgennard Can we have an error message without the stack trace? Especially when there are multiple ones it gets messy fast (and currently I have multiple ones on purpose - one set contains absolute paths for "windows" the other for "linux" + the always working "main" set that uses relative paths.
