### ISSUE TITLE
Extension activation failed on version 7.0.12

### ISSUE THREAD

**Issue by rudation** [spgennard/vscode_cobol#263]
**Describe the bug**
After upgrading to version 7.0.12 I get an error during activation of the extension. I reverted to previous version (7.0.11), everything worked ok.:

[2021-01-22 11:49:36.131] [exthost] [info] ExtensionService#_doActivateExtension bitlang.cobol {"startup":false,"extensionId":{"value":"bitlang.cobol","_lower":"bitlang.cobol"},"activationEvent":"onFileSystem:file"}
[2021-01-22 11:49:36.132] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/piotrek/.vscode-server/extensions/bitlang.cobol-7.0.12/dist/extension
(...)
**[2021-01-22 11:49:36.312] [exthost] [error] Activating extension bitlang.cobol failed due to an error:**
**[2021-01-22 11:49:36.315] [exthost] [error] TypeError: Cannot read property 'v4' of undefined**
	at Object.3987 (/home/piotrek/.vscode-server/extensions/bitlang.cobol-7.0.12/dist/extension.js:2:95993)
	at n (/home/piotrek/.vscode-server/extensions/bitlang.cobol-7.0.12/dist/extension.js:2:212654)
	at Object.112 (/home/piotrek/.vscode-server/extensions/bitlang.cobol-7.0.12/dist/extension.js:2:116293)
	at n (/home/piotrek/.vscode-server/extensions/bitlang.cobol-7.0.12/dist/extension.js:2:212654)
	at /home/piotrek/.vscode-server/extensions/bitlang.cobol-7.0.12/dist/extension.js:2:213095
	at Object.<anonymous> (/home/piotrek/.vscode-server/extensions/bitlang.cobol-7.0.12/dist/extension.js:2:213103)
	at Module._compile (internal/modules/cjs/loader.js:955:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
	at Module.load (internal/modules/cjs/loader.js:811:32)
	at Function.Module._load (internal/modules/cjs/loader.js:723:14)
	at Function.t._load (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1116:657)
	at Function.i._load (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1085:334)
	at Function.n._load (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1081:567)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.r [as __$__nodeRequire] (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/loader.js:20:263)
	at p._loadCommonJSModule (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1086:631)
	at p._doActivateExtension (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:982:742)
	at p._activateExtension (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:981:822)
	at Object.actualActivateExtension (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:979:453)
	at h._activateExtension (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:703:603)
	at /home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:703:281
	at Array.map (<anonymous>)
	at h._activateExtensions (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:703:269)
	at h.activateByEvent (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:700:745)
	at p._activateByEvent (/home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:980:300)
	at /home/piotrek/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:989:111
	at processTicksAndRejections (internal/process/task_queues.js:94:5)

**To Reproduce**
Start VS Code, try to use any of extension functions. Eg. the "Outline" tab is not filled with sections, divisions... It;s empty.

**Desktop (please complete the following information):**
 - OS : Windows 10.
 - VS Code version 1.52.1, Workspace is working as Remote on SSH. 
 - Remote machine is Red Hat Linux 7.8

**Comment by rudation** [comment]
Works fine after update to 7.0.14. Thanks, I'm closing this issue.
