### ISSUE TITLE
Performance issue since last update

### ISSUE THREAD

**Issue by Ldspout** [spgennard/vscode_cobol#306]
Hi,

I'm unable to work with large files since the last update.

The log says : 

```
2021-12-02 10:10:28.835] [renderer1] [error] Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at E.get kind [as kind] (vscode-file://vscode-app/c:/Users/xxxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:159:38017)
    at u (vscode-file://vscode-app/c:/Users/xxxx/AppD
ata/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js```

I've disabled all the extension and it seems it's the COBOL one which is causing problems.
I've set the JSON max items computed up to 100 000, but it's the same behaviour.

the side minimap appears after a very long time (when it works).

Any help would be helpful.

thank you !
L.

**Comment by GitMensch** [comment]
So the same file works with an earlier version fine? Please go to the extension view, then click on the gear icon of the extension and use "install another version" using an old one, then do the necessary restart and recheck - do so until you find the exact version where it did not work (nice side effect: you'll force a re-install also of the current version and have a workaround until this issue is fixed.

**Comment by spgennard** [comment]
@GitMensch and @Ldspout - Please both of you beware that the minimap feature is not provided by this extension

**Comment by GitMensch** [comment]
As far as I've understood that the minimap is just a symptom not the problem. But of course it doesn't harm to disable it in the menu to ensure that it doesn't have anything to do with the issue.

**Comment by spgennard** [comment]
The minimap uses TextMate grammar for the source being edited and creates a view from it.... no code in an extension is ever executed because it does not need to be, so I am unsure how it could be a symptom of something else related to this extension.

**Comment by Ldspout** [comment]
Hi,
thank you for your quick response.
I've tried to install an older version and I'v got the same issue. Trying to install older VSCode version too : same result.
Maybe it's something broken on my side.

Anyway, the minimap appears a very long time for 6000 lines source code and a very very long time for a 9000 lines code.

However, I've noticed the huge amount of processes tied to VS Code : 
![image](https://user-images.githubusercontent.com/55392454/144443343-e5229f28-816d-434d-aa29-f121971536bd.png)

I don't konw if it is the common behaviour.
I've tried other cobol extension (but with fewer features), there is no slowdown.

**Comment by GitMensch** [comment]
vscode spawns a lot of processes, that's normal and not a problem for modern machines. Some browsers even have one process per "active" tab. If both older versions of vscode and of this extension does not chance then "since last update" is definitely wrong - please edit the issue title.

To recap:

* it does happen with current and older versions of vscode
* it does happen with current and older versions of bitlang.cobol
* it does not happen with other extensions

Question to the later: Do they provide a symbol provider (so you can ctrl+click to get to the definition of a variable) and breadcrumb navigation / outline?
Suggestion to the later: a _similar_ extension that shares some features of this one is the bitlang.gnucobol extension, you may want to try that, even when not using GnuCOBOL.

It is still interesting to check  _what_ the actual issue is.
Can you please share your extension settings?

**Comment by spgennard** [comment]
> it does not happen with other extensions
I disagree, I see some slow down with other languages with large files, it all depends on the number of tokens that the language has and how complex the language & source code is.

> Question to the later: Do they provide a symbol provider (so you can ctrl+click to get to the definition of a variable) and breadcrumb navigation / outline?

This is not a relevant or useful question to ask, @GitMensch, if you take a look at the vscode sources to see how the minimap is implemented you will find it has nothing to do with symbol providers or document providers, please kindly refrain from guessing, as it can frustrate people.

The most time-consuming feature of this extension is the source scanning, so I further confirmed that this extension was not contributing to the issue via any supplied language provider extensions, by disabling all source scanning, thus "dumbing" down the extension and it behaved just the same.    

If it had changed behaviour or speed it would have been an indication that something in this extension needed some attention but unfortunately for the issue in question, it remained the same.

**Comment by GitMensch** [comment]
I miss some information. As I've noted I'm of the opinion that the minimap was the symptom of vscode doing extension work instead of its minimap. I don't know of any other evidence.
Also: if the same minimap has no issue with other COBOL extensions then it is likely not the minimap producing the issue at hand.

> The most time-consuming feature of this extension is the source scanning, so I further confirmed that this extension was not contributing to the issue via any supplied language provider extensions, by disabling all source scanning, thus "dumbing" down the extension and it behaved just the same.

So you actually could reproduce it?

When saying that the most-time consuming feature is the work needed to provide the data for the symbol provider and outline, why do you say directly before that this is not a useful question to ask?

... but I've understood the point you made that this issue is out of my scope, so I'll only keep reading here.
🤐

**Comment by spgennard** [comment]
> So you actually could reproduce it?
I just created a very large fake COBOL file

> When saying that the most-time consuming feature is the work needed to provide the data for the symbol provider and outline, why do you say directly before that this is not a useful question to ask?

>@GitMensch and @Ldspout - Please both of you beware that the minimap feature is not provided by this extension

I already knew how the minimap worked, so I was using this to demonstrate to you @GitMensch, that it was not something that this extension was doing.

**Comment by Ldspout** [comment]
Hello,

thank you for the responses.
I found that turning "editor.guides.bracketPairs" to false solved the problem.
Can you reproduce this on a big file ?
all the best,
L.

**Comment by spgennard** [comment]
Thanks for your reply, it does make faster

**Comment by vladhietala** [comment]
I'm also having performance issues. Looks like the problem was introduced in version 7.12.0.

When I open a 10k line cobol program (don't blame me, it's legacy code), the output of the Log window spams this callstack continuously, syntax highlighting isn't applied, and indentation guides aren't shown. 
```
[2021-12-09 14:03:34.332] [renderer1] [error] Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at y.read (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:560:23031)
    at b.peek (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:560:22430)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49576)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
    at b.parseList (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:49648)
    at b.parseChild (vscode-file://vscode-app/c:/Users/feliciano.kava/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:166:50393)
```

When I install 6.11.1 version I can work. In my configuration bracketPairs are always disabled. After my urgent activities I can give you more information about this issue.
